GET http://localhost:3000/subscribers
Content-Type: application/json

###

GET http://localhost:3000/subscribers/6112468e944bf9264c802e42
Content-Type: application/json

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Luke Petrocochino",
    "subscribedToChannel": "YouTube"
}

###

PATCH http://localhost:3000/subscribers/61124f3114736d378c661cbc
Content-Type: application/json

{
    "name": "Luke Petro",
    "subscribedToChannel": "Coodash"
}

###

DELETE http://localhost:3000/subscribers/61124f3114736d378c661cbc
Content-Type: application/json